theme: jekyll-theme-minimal
title: Digital Scholarship Workshop Series - Web Scraping
description: Jupyter Notebooks for exploring the practice and possibilities of web scraping.  You can find the complete list of Digital Scholarhsip Workshops here: You can find a directory of the currently available tutorials here:  [https://librarybeales.github.io/dsworkshops/](https://librarybeales.github.io/dsworkshops/)
show_downloads: true # shows download links for the repository
logo: # can easily be replaced with an institutional logo by uploading a new file
